-- Generated by `pnpm db:seed:sql` from content/*.csv. Do not edit by hand.
begin;
insert into tracks (id, ord, name, description, icon, has_diagnostic) values ('add', 1, '덧셈과 뺄셈', '10 이하 덧셈부터 한 단계씩', '/site/icon-addsub.png', true) on conflict (id) do update set ord = excluded.ord, name = excluded.name, description = excluded.description, icon = excluded.icon, has_diagnostic = excluded.has_diagnostic;
insert into tracks (id, ord, name, description, icon, has_diagnostic) values ('times', 2, '구구단', '2단부터 9단까지 곱셈구구', '/site/icon-muldiv.png', true) on conflict (id) do update set ord = excluded.ord, name = excluded.name, description = excluded.description, icon = excluded.icon, has_diagnostic = excluded.has_diagnostic;
insert into tracks (id, ord, name, description, icon, has_diagnostic) values ('tap', 3, '1~9 빨리 누르기', '숫자를 1부터 9까지 순서대로 빠르게', '/site/icon-tap.svg', false) on conflict (id) do update set ord = excluded.ord, name = excluded.name, description = excluded.description, icon = excluded.icon, has_diagnostic = excluded.has_diagnostic;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P1_INTU', 1, 'SA', 1, '+1 직관', 'intuition', 1, '더하기 1은 다음 수. 1 다음 2, 2 다음 3…', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P1_COMM', 2, 'SA', 1, '+1 교환법칙', 'commutative', 1, '덧셈은 순서를 바꿔도 같아요. 2+1=1+2', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P2_INTRO', 3, 'SA', 1, '+2 도입', 'intro', 2, '더하기 2는 두 칸 간 수. 2→→4, 3→→5', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P2_INTU', 4, 'SA', 1, '+2 직관', 'intuition', 2, '더하기 2는 두 칸 간 수. 2→→4, 3→→5', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P2_COMM', 5, 'SA', 1, '+2 교환법칙', 'commutative', 2, '3+2=2+3', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P3_INTRO', 6, 'SA', 1, '+3 도입', 'intro', 3, '더하기 3은 세 칸 간 수. 2→→→5, 3→→→6', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P3_INTU', 7, 'SA', 1, '+3 직관', 'intuition', 3, '더하기 3은 세 칸 간 수. 2→→→5, 3→→→6', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P3_COMM', 8, 'SA', 1, '+3 교환법칙', 'commutative', 3, '4+3=3+4', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P4_INTRO', 9, 'SA', 1, '+4 도입', 'intro', 4, '더하기 4는 네 칸 간 수. 2→→→→6, 3→→→→7', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P4_INTU', 10, 'SA', 1, '+4 직관', 'intuition', 4, '더하기 4는 네 칸 간 수. 2→→→→6, 3→→→→7', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P4_COMM', 11, 'SA', 1, '+4 교환법칙', 'commutative', 4, '4+3=3+4', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P5_INTRO', 12, 'SA', 1, '+5 도입', 'intro', 5, '더하기 5는 다섯 칸 간 수. 2→→→→→7, 3→→→→→8', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P5_INTU', 13, 'SA', 1, '+5 직관', 'intuition', 5, '더하기 5는 다섯 칸 간 수.', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_P5_COMM', 14, 'SA', 1, '+5 교환법칙', 'commutative', 5, '5+2=2+5', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('ADD_COMP10', 15, 'SA', 1, '10의 보수', 'complement10', null, '더해서 10이 되는 짝을 찾아요. 9와 1, 8과 2…', 'per_set', 12, 3, 'add') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_2', 101, 'SC', 29, '구구단 2단', 'times_table', 2, '2단은 2씩 커져요. 2, 4, 6, 8, 10…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_5', 102, 'SC', 29, '구구단 5단', 'times_table', 5, '5단은 5씩 커져요. 5, 10, 15, 20, 25…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_3', 103, 'SC', 29, '구구단 3단', 'times_table', 3, '3단은 3씩 커져요. 3, 6, 9, 12, 15…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_4', 104, 'SC', 29, '구구단 4단', 'times_table', 4, '4단은 4씩 커져요. 4, 8, 12, 16, 20…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_MIX_A', 105, 'SC', 31, '2·5·3·4단 섞어서', 'times_mixed', null, '섞여 나와도 몇 단인지 먼저 보고, 그 단을 떠올려요.', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_6', 106, 'SC', 30, '구구단 6단', 'times_table', 6, '6단은 6씩 커져요. 6, 12, 18, 24, 30…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_9', 107, 'SC', 30, '구구단 9단', 'times_table', 9, '9단은 9씩 커져요. 9, 18, 27, 36, 45…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_7', 108, 'SC', 30, '구구단 7단', 'times_table', 7, '7단은 7씩 커져요. 7, 14, 21, 28, 35…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_8', 109, 'SC', 30, '구구단 8단', 'times_table', 8, '8단은 8씩 커져요. 8, 16, 24, 32, 40…', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TIMES_MIX_B', 110, 'SC', 31, '6·9·7·8단 섞어서', 'times_mixed', null, '섞여 나와도 몇 단인지 먼저 보고, 그 단을 떠올려요.', 'per_set', 20, 3, 'times') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TAP_L1', 201, 'TAP', null, '1~9 빨리 누르기 1단계', 'tap_sequence', null, '1부터 9까지 순서대로 눌러요. 12초 안에 실수 없이!', 'per_set', 12, 3, 'tap') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TAP_L2', 202, 'TAP', null, '1~9 빨리 누르기 2단계', 'tap_sequence', null, '1부터 9까지 순서대로 눌러요. 8초 안에 실수 없이!', 'per_set', 8, 3, 'tap') on conflict (id) do nothing;
insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values ('TAP_L3', 203, 'TAP', null, '1~9 빨리 누르기 3단계', 'tap_sequence', null, '1부터 9까지 순서대로 눌러요. 5초 안에 실수 없이!', 'per_set', 5, 3, 'tap') on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P01', 'ADD_P1_INTU', 1, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P02', 'ADD_P1_INTU', 2, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P03', 'ADD_P1_COMM', 3, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P04', 'ADD_P1_COMM', 4, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P05', 'ADD_P2_INTRO', 5, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P06', 'ADD_P2_INTRO', 6, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P07', 'ADD_P2_INTU', 7, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P08', 'ADD_P2_INTU', 8, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P09', 'ADD_P2_COMM', 9, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P10', 'ADD_P2_COMM', 10, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P11', 'ADD_P3_INTRO', 11, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P12', 'ADD_P3_INTRO', 12, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P13', 'ADD_P3_INTU', 13, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P14', 'ADD_P3_INTU', 14, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P15', 'ADD_P3_COMM', 15, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P16', 'ADD_P3_COMM', 16, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P17', 'ADD_P4_INTRO', 17, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P18', 'ADD_P4_INTRO', 18, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P19', 'ADD_P4_INTU', 19, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P20', 'ADD_P4_INTU', 20, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P21', 'ADD_P4_COMM', 21, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P22', 'ADD_P4_COMM', 22, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P23', 'ADD_P5_INTRO', 23, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P24', 'ADD_P5_INTRO', 24, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P25', 'ADD_P5_INTU', 25, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P26', 'ADD_P5_COMM', 26, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P27', 'ADD_P5_COMM', 27, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P28', 'ADD_COMP10', 28, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('SA-P29', 'ADD_COMP10', 29, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P01', 'TIMES_2', 1, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P02', 'TIMES_2', 2, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P03', 'TIMES_5', 3, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P04', 'TIMES_5', 4, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P05', 'TIMES_3', 5, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P06', 'TIMES_3', 6, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P07', 'TIMES_4', 7, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P08', 'TIMES_4', 8, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P09', 'TIMES_MIX_A', 9, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P10', 'TIMES_6', 10, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P11', 'TIMES_6', 11, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P12', 'TIMES_9', 12, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P13', 'TIMES_9', 13, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P14', 'TIMES_7', 14, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P15', 'TIMES_7', 15, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P16', 'TIMES_8', 16, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P17', 'TIMES_8', 17, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('GG-P18', 'TIMES_MIX_B', 18, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('TAP-P01', 'TAP_L1', 1, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('TAP-P02', 'TAP_L2', 2, 0) on conflict (id) do nothing;
insert into item_sets (id, skill_id, page, ord) values ('TAP-P03', 'TAP_L3', 3, 0) on conflict (id) do nothing;
update item_sets s set ord = r.rn from (select id, row_number() over (partition by skill_id order by page) as rn from item_sets) r where r.id = s.id;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P01', 1, 1, '+', 1, 'result', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P01', 2, 2, '+', 1, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P01', 3, 3, '+', 1, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P01', 4, 4, '+', 1, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P01', 5, 5, '+', 1, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P02', 1, 6, '+', 1, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P02', 2, 7, '+', 1, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P02', 3, 8, '+', 1, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P02', 4, 9, '+', 1, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 1, 2, '+', 1, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 2, 1, '+', 2, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 3, 3, '+', 1, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 4, 1, '+', 3, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 5, 4, '+', 1, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 6, 1, '+', 4, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 7, 5, '+', 1, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P03', 8, 1, '+', 5, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 1, 6, '+', 1, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 2, 1, '+', 6, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 3, 7, '+', 1, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 4, 1, '+', 7, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 5, 8, '+', 1, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 6, 1, '+', 8, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 7, 9, '+', 1, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P04', 8, 1, '+', 9, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 1, 2, '+', 1, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 2, 2, '+', 2, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 3, 3, '+', 1, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 4, 3, '+', 2, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 5, 4, '+', 1, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 6, 4, '+', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 7, 5, '+', 1, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P05', 8, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 1, 6, '+', 1, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 2, 6, '+', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 3, 7, '+', 1, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 4, 7, '+', 2, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 5, 8, '+', 1, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 6, 8, '+', 2, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P06', 7, 9, '+', 1, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P07', 1, 2, '+', 2, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P07', 2, 3, '+', 2, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P07', 3, 4, '+', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P07', 4, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P07', 5, 6, '+', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P08', 1, 4, '+', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P08', 2, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P08', 3, 6, '+', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P08', 4, 7, '+', 2, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P08', 5, 8, '+', 2, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 1, 2, '+', 2, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 2, 3, '+', 2, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 3, 2, '+', 3, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 4, 4, '+', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 5, 2, '+', 4, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 6, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P09', 7, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 1, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 2, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 3, 6, '+', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 4, 2, '+', 6, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 5, 7, '+', 2, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 6, 2, '+', 7, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 7, 8, '+', 2, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P10', 8, 2, '+', 8, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 1, 2, '+', 2, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 2, 2, '+', 3, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 3, 3, '+', 3, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 4, 4, '+', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 5, 4, '+', 3, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 6, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P11', 7, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P12', 1, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P12', 2, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P12', 3, 6, '+', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P12', 4, 6, '+', 3, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P12', 5, 7, '+', 2, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P12', 6, 7, '+', 3, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P13', 1, 1, '+', 3, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P13', 2, 2, '+', 3, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P13', 3, 3, '+', 3, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P13', 4, 4, '+', 3, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P13', 5, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P14', 1, 3, '+', 3, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P14', 2, 4, '+', 3, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P14', 3, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P14', 4, 6, '+', 3, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P14', 5, 7, '+', 3, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 1, 3, '+', 3, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 2, 4, '+', 3, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 3, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 4, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 5, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 6, 6, '+', 3, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P15', 7, 3, '+', 6, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 1, 4, '+', 3, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 2, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 3, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 4, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 5, 6, '+', 3, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 6, 3, '+', 6, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 7, 7, '+', 3, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P16', 8, 3, '+', 7, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P17', 1, 4, '+', 1, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P17', 2, 1, '+', 4, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P17', 3, 2, '+', 4, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P17', 4, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P17', 5, 4, '+', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P17', 6, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P18', 1, 2, '+', 4, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P18', 2, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P18', 3, 4, '+', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P18', 4, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P18', 5, 6, '+', 4, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P19', 1, 1, '+', 4, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P19', 2, 2, '+', 4, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P19', 3, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P19', 4, 4, '+', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P19', 5, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P20', 1, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P20', 2, 4, '+', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P20', 3, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P20', 4, 6, '+', 4, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P21', 1, 1, '+', 4, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P21', 2, 4, '+', 1, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P21', 3, 2, '+', 4, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P21', 4, 4, '+', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P21', 5, 3, '+', 4, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P21', 6, 4, '+', 3, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P22', 1, 4, '+', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P22', 2, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P22', 3, 4, '+', 5, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P22', 4, 6, '+', 4, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P22', 5, 4, '+', 6, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P23', 1, 5, '+', 1, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P23', 2, 1, '+', 5, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P23', 3, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P23', 4, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P23', 5, 4, '+', 5, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P23', 6, 5, '+', 5, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P24', 1, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P24', 2, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P24', 3, 4, '+', 5, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P24', 4, 5, '+', 5, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P25', 1, 1, '+', 5, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P25', 2, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P25', 3, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P25', 4, 4, '+', 5, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P25', 5, 5, '+', 5, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 1, 5, '+', 1, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 2, 1, '+', 5, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 3, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 4, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 5, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 6, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 7, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P26', 8, 4, '+', 5, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 1, 5, '+', 2, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 2, 2, '+', 5, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 3, 5, '+', 3, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 4, 3, '+', 5, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 5, 5, '+', 4, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 6, 4, '+', 5, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P27', 7, 5, '+', 5, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P28', 1, 9, '+', 1, 'operand2', 1) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P28', 2, 8, '+', 2, 'operand2', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P28', 3, 7, '+', 3, 'operand2', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P28', 4, 6, '+', 4, 'operand2', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P28', 5, 5, '+', 5, 'operand2', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P29', 1, 5, '+', 5, 'operand2', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P29', 2, 4, '+', 6, 'operand2', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P29', 3, 3, '+', 7, 'operand2', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P29', 4, 2, '+', 8, 'operand2', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('SA-P29', 5, 1, '+', 9, 'operand2', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 1, 2, '×', 1, 'result', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 2, 2, '×', 2, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 3, 2, '×', 3, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 4, 2, '×', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 5, 2, '×', 5, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 6, 2, '×', 6, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 7, 2, '×', 7, 'result', 14) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 8, 2, '×', 8, 'result', 16) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P01', 9, 2, '×', 9, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 1, 1, '×', 2, 'result', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 2, 2, '×', 2, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 3, 3, '×', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 4, 4, '×', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 5, 5, '×', 2, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 6, 6, '×', 2, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 7, 7, '×', 2, 'result', 14) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 8, 8, '×', 2, 'result', 16) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P02', 9, 9, '×', 2, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 1, 5, '×', 1, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 2, 5, '×', 2, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 3, 5, '×', 3, 'result', 15) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 4, 5, '×', 4, 'result', 20) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 5, 5, '×', 5, 'result', 25) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 6, 5, '×', 6, 'result', 30) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 7, 5, '×', 7, 'result', 35) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 8, 5, '×', 8, 'result', 40) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P03', 9, 5, '×', 9, 'result', 45) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 1, 1, '×', 5, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 2, 2, '×', 5, 'result', 10) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 3, 3, '×', 5, 'result', 15) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 4, 4, '×', 5, 'result', 20) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 5, 5, '×', 5, 'result', 25) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 6, 6, '×', 5, 'result', 30) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 7, 7, '×', 5, 'result', 35) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 8, 8, '×', 5, 'result', 40) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P04', 9, 9, '×', 5, 'result', 45) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 1, 3, '×', 1, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 2, 3, '×', 2, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 3, 3, '×', 3, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 4, 3, '×', 4, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 5, 3, '×', 5, 'result', 15) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 6, 3, '×', 6, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 7, 3, '×', 7, 'result', 21) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 8, 3, '×', 8, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P05', 9, 3, '×', 9, 'result', 27) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 1, 1, '×', 3, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 2, 2, '×', 3, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 3, 3, '×', 3, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 4, 4, '×', 3, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 5, 5, '×', 3, 'result', 15) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 6, 6, '×', 3, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 7, 7, '×', 3, 'result', 21) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 8, 8, '×', 3, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P06', 9, 9, '×', 3, 'result', 27) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 1, 4, '×', 1, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 2, 4, '×', 2, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 3, 4, '×', 3, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 4, 4, '×', 4, 'result', 16) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 5, 4, '×', 5, 'result', 20) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 6, 4, '×', 6, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 7, 4, '×', 7, 'result', 28) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 8, 4, '×', 8, 'result', 32) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P07', 9, 4, '×', 9, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 1, 1, '×', 4, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 2, 2, '×', 4, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 3, 3, '×', 4, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 4, 4, '×', 4, 'result', 16) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 5, 5, '×', 4, 'result', 20) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 6, 6, '×', 4, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 7, 7, '×', 4, 'result', 28) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 8, 8, '×', 4, 'result', 32) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P08', 9, 9, '×', 4, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 1, 2, '×', 7, 'result', 14) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 2, 5, '×', 4, 'result', 20) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 3, 3, '×', 8, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 4, 4, '×', 6, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 5, 2, '×', 9, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 6, 5, '×', 7, 'result', 35) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 7, 3, '×', 6, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 8, 4, '×', 9, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P09', 9, 4, '×', 8, 'result', 32) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 1, 6, '×', 1, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 2, 6, '×', 2, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 3, 6, '×', 3, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 4, 6, '×', 4, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 5, 6, '×', 5, 'result', 30) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 6, 6, '×', 6, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 7, 6, '×', 7, 'result', 42) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 8, 6, '×', 8, 'result', 48) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P10', 9, 6, '×', 9, 'result', 54) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 1, 1, '×', 6, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 2, 2, '×', 6, 'result', 12) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 3, 3, '×', 6, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 4, 4, '×', 6, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 5, 5, '×', 6, 'result', 30) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 6, 6, '×', 6, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 7, 7, '×', 6, 'result', 42) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 8, 8, '×', 6, 'result', 48) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P11', 9, 9, '×', 6, 'result', 54) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 1, 9, '×', 1, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 2, 9, '×', 2, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 3, 9, '×', 3, 'result', 27) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 4, 9, '×', 4, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 5, 9, '×', 5, 'result', 45) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 6, 9, '×', 6, 'result', 54) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 7, 9, '×', 7, 'result', 63) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 8, 9, '×', 8, 'result', 72) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P12', 9, 9, '×', 9, 'result', 81) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 1, 1, '×', 9, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 2, 2, '×', 9, 'result', 18) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 3, 3, '×', 9, 'result', 27) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 4, 4, '×', 9, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 5, 5, '×', 9, 'result', 45) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 6, 6, '×', 9, 'result', 54) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 7, 7, '×', 9, 'result', 63) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 8, 8, '×', 9, 'result', 72) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P13', 9, 9, '×', 9, 'result', 81) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 1, 7, '×', 1, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 2, 7, '×', 2, 'result', 14) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 3, 7, '×', 3, 'result', 21) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 4, 7, '×', 4, 'result', 28) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 5, 7, '×', 5, 'result', 35) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 6, 7, '×', 6, 'result', 42) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 7, 7, '×', 7, 'result', 49) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 8, 7, '×', 8, 'result', 56) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P14', 9, 7, '×', 9, 'result', 63) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 1, 1, '×', 7, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 2, 2, '×', 7, 'result', 14) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 3, 3, '×', 7, 'result', 21) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 4, 4, '×', 7, 'result', 28) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 5, 5, '×', 7, 'result', 35) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 6, 6, '×', 7, 'result', 42) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 7, 7, '×', 7, 'result', 49) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 8, 8, '×', 7, 'result', 56) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P15', 9, 9, '×', 7, 'result', 63) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 1, 8, '×', 1, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 2, 8, '×', 2, 'result', 16) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 3, 8, '×', 3, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 4, 8, '×', 4, 'result', 32) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 5, 8, '×', 5, 'result', 40) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 6, 8, '×', 6, 'result', 48) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 7, 8, '×', 7, 'result', 56) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 8, 8, '×', 8, 'result', 64) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P16', 9, 8, '×', 9, 'result', 72) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 1, 1, '×', 8, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 2, 2, '×', 8, 'result', 16) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 3, 3, '×', 8, 'result', 24) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 4, 4, '×', 8, 'result', 32) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 5, 5, '×', 8, 'result', 40) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 6, 6, '×', 8, 'result', 48) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 7, 7, '×', 8, 'result', 56) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 8, 8, '×', 8, 'result', 64) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P17', 9, 9, '×', 8, 'result', 72) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 1, 6, '×', 7, 'result', 42) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 2, 9, '×', 4, 'result', 36) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 3, 7, '×', 8, 'result', 56) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 4, 8, '×', 6, 'result', 48) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 5, 6, '×', 9, 'result', 54) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 6, 9, '×', 7, 'result', 63) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 7, 7, '×', 6, 'result', 42) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 8, 8, '×', 9, 'result', 72) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('GG-P18', 9, 8, '×', 7, 'result', 56) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 1, 1, '+', 0, 'result', 1) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 2, 2, '+', 0, 'result', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 3, 3, '+', 0, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 4, 4, '+', 0, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 5, 5, '+', 0, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 6, 6, '+', 0, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 7, 7, '+', 0, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 8, 8, '+', 0, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P01', 9, 9, '+', 0, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 1, 1, '+', 0, 'result', 1) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 2, 2, '+', 0, 'result', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 3, 3, '+', 0, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 4, 4, '+', 0, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 5, 5, '+', 0, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 6, 6, '+', 0, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 7, 7, '+', 0, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 8, 8, '+', 0, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P02', 9, 9, '+', 0, 'result', 9) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 1, 1, '+', 0, 'result', 1) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 2, 2, '+', 0, 'result', 2) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 3, 3, '+', 0, 'result', 3) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 4, 4, '+', 0, 'result', 4) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 5, 5, '+', 0, 'result', 5) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 6, 6, '+', 0, 'result', 6) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 7, 7, '+', 0, 'result', 7) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 8, 8, '+', 0, 'result', 8) on conflict (set_id, ord) do nothing;
insert into items (set_id, ord, a, op, b, blank, answer) values ('TAP-P03', 9, 9, '+', 0, 'result', 9) on conflict (set_id, ord) do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P1_INTU', 'accuracy', '더하기 1은 ''바로 다음 수''예요', '수를 셀 때 1, 2, 3, 4… 하고 하나씩 커지지요?
더하기 1은 그 수의 바로 다음 수를 말하면 돼요.
4 + 1은 4 다음 수, 5예요. 수직선에서 오른쪽으로 딱 한 칸!', '소리 내어 읽어 봐요: "4 더하기 1은 4 다음, 5"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P1_INTU', 'speed', '다음 수를 바로 떠올려요', '다 맞혔어요! 이제 손가락으로 세지 않고 다음 수를 바로 말하는 연습을 해요.
수를 보면 머릿속에서 ''다음!'' 하고 한 칸 뛰어요.', '연습할 때 문제를 보자마자 입으로 먼저 말해 보세요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P1_COMM', 'accuracy', '1 + 5도 5 + 1과 같아요', '더하기는 순서를 바꿔도 답이 같아요. 이것을 ''교환법칙''이라고 해요.
1 + 5를 보면 앞뒤를 바꿔 5 + 1로 생각해요. 5 다음 수, 6!
큰 수에서 시작하면 훨씬 쉬워요.', '큰 수를 먼저 읽기: "1 더하기 5는 5 더하기 1, 6"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P1_COMM', 'speed', '큰 수부터 시작하면 빨라져요', '1이 앞에 있어도 큰 수에서 출발하면 한 칸만 가면 돼요.
1 + 7 → 7 + 1 → 8. 바꾸는 것을 머릿속에서 한 번에 해 봐요.', '''1 더하기''가 보이면 바로 ''큰 수 다음''을 떠올려요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P2_INTRO', 'accuracy', '더하기 2는 두 칸 간 수예요', '수직선에서 오른쪽으로 두 번 뛰면 더하기 2예요.
3 + 2 → 3에서 한 칸(4), 두 칸(5). 그래서 5!
더하기 1과 더하기 2를 번갈아 보면서 한 칸인지 두 칸인지 잘 봐요.', '뛸 때마다 "하나, 둘" 하고 세어 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P2_INTRO', 'speed', '두 칸을 한 번에 뛰어요', '다 맞혔어요! 이제 한 칸씩 세지 말고 두 칸을 한 번에 건너뛰어 봐요.
2, 4, 6, 8, 10처럼 둘씩 뛰어 세기를 소리 내어 해 보면 빨라져요.', '둘씩 뛰어 세기(2, 4, 6, 8, 10)를 세 번 말해 보세요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P2_INTU', 'accuracy', '두 칸 간 수를 떠올려요', '더하기 2는 두 칸 간 수. 2→→4, 3→→5.
하나 건너뛴 수를 찾으면 돼요. 6 + 2는 7을 건너뛰고 8!', '화살표 두 개(→→)를 손가락으로 그려 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P2_INTU', 'speed', '''하나 건너뛰기''를 눈으로 해요', '정확하게 잘 풀었어요. 수를 보면 다음 수를 건너뛰고 그 다음 수를 바로 말해요.
5 + 2 → (6 건너뛰고) 7.', '문제를 보자마자 ''건너뛰고!''를 떠올려요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P2_COMM', 'accuracy', '2 + 4는 4 + 2와 같아요', '더하기는 순서를 바꿔도 같아요. 3 + 2 = 2 + 3.
2가 앞에 있으면 뒤의 큰 수에서 두 칸 가요.
2 + 5 → 5에서 두 칸 → 7.', '읽어 봐요: "2 더하기 5는 5 더하기 2, 7"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P2_COMM', 'speed', '큰 수에서 두 칸', '정답은 모두 맞았어요! 2가 앞에 나와도 바로 큰 수로 출발하는 습관을 들여요.', '''2 더하기''가 보이면 뒤의 수에서 두 칸!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P3_INTRO', 'accuracy', '더하기 3은 세 칸 간 수예요', '수직선에서 오른쪽으로 세 번 뛰면 더하기 3.
2 + 3 → 3, 4, 5. 그래서 5!
뛴 횟수가 3번인지 꼭 확인해요. 한 번 덜 뛰면 하나 작은 답이 나와요.', '뛸 때 "하나, 둘, 셋"을 손가락 세 개로 세어 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P3_INTRO', 'speed', '세 칸을 덩어리로 봐요', '다 맞혔어요! 이제 세 칸을 한 번에 보는 연습을 해요.
3, 6, 9처럼 셋씩 뛰어 세기를 말해 보면 감이 생겨요.', '''+3''은 ''둘 건너뛰고 그 다음''이에요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P3_INTU', 'accuracy', '세 칸 간 수를 떠올려요', '더하기 3은 세 칸 간 수. 2→→→5, 3→→→6.
4 + 3은 5, 6을 건너뛰고 7!', '화살표 세 개(→→→)를 그려 보고 도착한 수를 말해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P3_INTU', 'speed', '도착하는 수를 바로 말해요', '정답은 모두 맞았어요. 세는 소리를 점점 작게, 마지막 수만 크게 말해 보세요.
4 + 3 → (5, 6) 7!', '마지막 수만 크게 말하는 연습이 속도를 높여요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P3_COMM', 'accuracy', '3 + 4는 4 + 3과 같아요', '순서를 바꿔도 더한 값은 같아요. 4 + 3 = 3 + 4.
3이 앞에 있으면 큰 수에서 세 칸 가요. 3 + 6 → 6에서 세 칸 → 9.', '읽어 봐요: "3 더하기 6은 6 더하기 3, 9"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P3_COMM', 'speed', '큰 수에서 세 칸', '다 맞혔어요! 작은 수가 앞에 나와도 큰 수에서 출발하는 것을 한 번에 해 봐요.', '''3 더하기''가 보이면 뒤의 수에서 세 칸!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P4_INTRO', 'accuracy', '더하기 4는 네 칸 간 수예요', '수직선에서 오른쪽으로 네 번 뛰면 더하기 4.
2 + 4 → 3, 4, 5, 6. 그래서 6!
4는 2와 2예요. 두 칸, 또 두 칸 뛰어도 돼요.', '+4를 ''+2 그리고 +2''로 나누어 생각해 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P4_INTRO', 'speed', '두 칸 + 두 칸', '정답은 모두 맞았어요! 네 칸을 하나씩 세면 느려요.
+2를 두 번 하면 +4. 3 + 4 → 5 → 7.', '+2를 빠르게 할 수 있으니 +4도 금방이에요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P4_INTU', 'accuracy', '네 칸 간 수를 떠올려요', '더하기 4는 네 칸 간 수. 2→→→→6, 3→→→→7.
화살표 네 개를 그리고 마지막에 도착한 수가 답이에요.', '손가락 네 개를 펴고 하나씩 접으며 확인해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P4_INTU', 'speed', '+2를 두 번으로 빠르게', '다 맞혔어요! 5 + 4는 5 → 7 → 9. 두 번만 뛰면 돼요.', '+4는 두 번 뛰기!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P4_COMM', 'accuracy', '4 + 3은 3 + 4와 같아요', '순서를 바꿔도 같아요. 4가 앞에 있어도, 4가 뒤에 있어도 더한 값은 똑같아요.
큰 수에서 작은 수만큼 가요. 4 + 5 → 5에서 네 칸 → 9.', '읽어 봐요: "4 더하기 5는 5 더하기 4, 9"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P4_COMM', 'speed', '큰 수에서 출발', '정답은 모두 맞았어요! 둘 중 큰 수를 먼저 찾고, 작은 수만큼 가는 순서를 몸에 익혀요.', '''어느 쪽이 커?''를 먼저 보는 습관!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P5_INTRO', 'accuracy', '더하기 5는 다섯 칸 간 수예요', '수직선에서 오른쪽으로 다섯 번 뛰면 더하기 5.
5는 한 손이에요! 손가락 다섯 개를 모두 펴서 세어 봐요.
2 + 5 → 3, 4, 5, 6, 7. 그래서 7!', '한 손(5)을 활짝 펴고 하나씩 세어요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P5_INTRO', 'speed', '''한 손''을 통째로 더해요', '다 맞혔어요! 5는 한 손이니까 하나씩 세지 않아도 돼요.
3 + 5는 ''3과 한 손'' → 8. 5와 짝이 되는 수를 기억해요: 5+1=6, 5+2=7, 5+3=8.', '5에 더하는 덧셈을 노래처럼 외워 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P5_INTU', 'accuracy', '다섯 칸 간 수를 떠올려요', '더하기 5는 다섯 칸 간 수.
4 + 5는 4에서 다섯 칸 → 9. 한 칸씩 정확히 다섯 번 뛰었는지 확인해요.', '뛴 횟수를 손가락으로 확인해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P5_INTU', 'speed', '5 묶음으로 보기', '정답은 모두 맞았어요! 4 + 5는 ''4와 한 손'', 9. 묶음으로 보면 바로 보여요.', '5 묶음 생각하기!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P5_COMM', 'accuracy', '5 + 2는 2 + 5와 같아요', '순서를 바꿔도 같아요. 2 + 5 = 5 + 2.
5에서 출발해 두 칸 가면 7. 큰 수에서 시작하면 쉬워요.', '읽어 봐요: "2 더하기 5는 5 더하기 2, 7"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_P5_COMM', 'speed', '5에서 출발', '다 맞혔어요! 5가 보이면 5에서 출발해 나머지 수만큼만 가요.', '5는 출발점!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_COMP10', 'accuracy', '더해서 10이 되는 짝', '10칸짜리 상자를 생각해요. 9칸이 차 있으면 빈 칸은 1칸이에요.
그래서 9 + □ = 10의 □는 1!
10의 짝: 9와 1, 8과 2, 7과 3, 6과 4, 5와 5.', '빈 칸을 세어 봐요. 빈 칸 수가 바로 답!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('ADD_COMP10', 'speed', '10의 짝을 외워요', '다 맞혔어요! 10의 짝(9와 1, 8과 2, 7과 3, 6과 4, 5와 5)을 노래처럼 외우면 바로 떠올라요.', '손가락 열 개 중 접힌 것과 펴진 것이 10의 짝이에요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_2', 'accuracy', '2단은 2씩 묶음이에요', '2 × 3은 ''2씩 3묶음''이라는 뜻이에요. 2을 세 번 더한 것과 같아요: 2 + 2 + 2 = 6.
2단은 2씩 뛰어 세면 나와요: 2, 4, 6, 8, 10, 12, 14, 16, 18.
순서를 바꾼 3 × 2도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "2 일은 2, 2 이 4, 2 삼 6…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_2', 'speed', '2단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
2단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"2 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_5', 'accuracy', '5단은 5씩 묶음이에요', '5 × 3은 ''5씩 3묶음''이라는 뜻이에요. 5을 세 번 더한 것과 같아요: 5 + 5 + 5 = 15.
5단은 5씩 뛰어 세면 나와요: 5, 10, 15, 20, 25, 30, 35, 40, 45.
순서를 바꾼 3 × 5도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "5 일은 5, 5 이 10, 5 삼 15…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_5', 'speed', '5단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
5단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"5 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_3', 'accuracy', '3단은 3씩 묶음이에요', '3 × 3은 ''3씩 3묶음''이라는 뜻이에요. 3을 세 번 더한 것과 같아요: 3 + 3 + 3 = 9.
3단은 3씩 뛰어 세면 나와요: 3, 6, 9, 12, 15, 18, 21, 24, 27.
순서를 바꾼 3 × 3도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "3 일은 3, 3 이 6, 3 삼 9…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_3', 'speed', '3단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
3단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"3 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_4', 'accuracy', '4단은 4씩 묶음이에요', '4 × 3은 ''4씩 3묶음''이라는 뜻이에요. 4을 세 번 더한 것과 같아요: 4 + 4 + 4 = 12.
4단은 4씩 뛰어 세면 나와요: 4, 8, 12, 16, 20, 24, 28, 32, 36.
순서를 바꾼 3 × 4도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "4 일은 4, 4 이 8, 4 삼 12…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_4', 'speed', '4단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
4단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"4 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_6', 'accuracy', '6단은 6씩 묶음이에요', '6 × 3은 ''6씩 3묶음''이라는 뜻이에요. 6을 세 번 더한 것과 같아요: 6 + 6 + 6 = 18.
6단은 6씩 뛰어 세면 나와요: 6, 12, 18, 24, 30, 36, 42, 48, 54.
순서를 바꾼 3 × 6도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "6 일은 6, 6 이 12, 6 삼 18…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_6', 'speed', '6단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
6단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"6 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_9', 'accuracy', '9단은 9씩 묶음이에요', '9 × 3은 ''9씩 3묶음''이라는 뜻이에요. 9을 세 번 더한 것과 같아요: 9 + 9 + 9 = 27.
9단은 9씩 뛰어 세면 나와요: 9, 18, 27, 36, 45, 54, 63, 72, 81.
순서를 바꾼 3 × 9도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "9 일은 9, 9 이 18, 9 삼 27…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_9', 'speed', '9단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
9단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"9 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_7', 'accuracy', '7단은 7씩 묶음이에요', '7 × 3은 ''7씩 3묶음''이라는 뜻이에요. 7을 세 번 더한 것과 같아요: 7 + 7 + 7 = 21.
7단은 7씩 뛰어 세면 나와요: 7, 14, 21, 28, 35, 42, 49, 56, 63.
순서를 바꾼 3 × 7도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "7 일은 7, 7 이 14, 7 삼 21…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_7', 'speed', '7단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
7단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"7 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_8', 'accuracy', '8단은 8씩 묶음이에요', '8 × 3은 ''8씩 3묶음''이라는 뜻이에요. 8을 세 번 더한 것과 같아요: 8 + 8 + 8 = 24.
8단은 8씩 뛰어 세면 나와요: 8, 16, 24, 32, 40, 48, 56, 64, 72.
순서를 바꾼 3 × 8도 답이 같아요. 곱하기도 순서를 바꿔도 같아요!', '소리 내어 외워 봐요: "8 일은 8, 8 이 16, 8 삼 24…"') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_8', 'speed', '8단을 노래처럼 바로 떠올려요', '다 맞혔어요! 이제 하나씩 더하지 말고 답을 바로 떠올려요.
8단을 처음부터 끝까지 리듬에 맞춰 세 번 외우면 빨라져요.', '"8 × 7"처럼 중간부터 물어봐도 바로 나올 때까지 연습해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_MIX_A', 'accuracy', '몇 단인지 먼저 봐요', '섞여 나오면 헷갈리기 쉬워요. 먼저 앞의 수를 보고 ''몇 단''인지 정해요.
4 × 6이면 4단: 4, 8, 12, 16, 20, 24. 그래서 24!
잘 안 떠오르면 순서를 바꿔 아는 단으로 생각해도 돼요 (4 × 6 = 6 × 4).', '틀린 문제의 단을 다시 한 번 처음부터 외워 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_MIX_A', 'speed', '섞여도 바로바로', '다 맞혔어요! 섞인 문제도 단을 정하는 시간을 줄이면 빨라져요.
2·5단은 특히 쉬워요: 5단은 끝자리가 0 아니면 5!', '자주 틀리는 곱셈 두세 개를 카드에 적어 두고 외워요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_MIX_B', 'accuracy', '큰 단은 아는 단으로 바꿔요', '6·7·8·9단은 어려워요. 순서를 바꾸면 아는 단이 될 때가 많아요.
9 × 4 = 4 × 9 = 36. 9단은 십의 자리와 일의 자리를 더하면 9가 돼요 (3+6=9).', '9단 비밀: 18, 27, 36, 45… 두 숫자를 더하면 언제나 9!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TIMES_MIX_B', 'speed', '어려운 짝을 집중해서', '다 맞혔어요! 6×7, 7×8, 8×6처럼 자주 헷갈리는 짝을 따로 외우면 빨라져요.
5, 6, 7, 8: 56 = 7 × 8.', '''5, 6, 7, 8 → 56 = 7 × 8''처럼 노래로 기억해요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TAP_L1', 'accuracy', '순서대로 차근차근', '다음에 누를 숫자를 먼저 입으로 말하고, 화면에서 찾아서 눌러요.
급하게 누르면 옆 숫자를 누르기 쉬워요. 1, 2, 3… 하나씩 정확하게!', '누르기 전에 숫자를 소리 내어 말해 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TAP_L1', 'speed', '12초 안에 끝내려면', '실수 없이 잘 눌렀어요! 이제 다음 숫자가 어디 있는지 미리 눈으로 찾아 두면 빨라져요.
지금 숫자를 누르는 동안 눈은 벌써 다음 숫자를 찾고 있어야 해요.', '손보다 눈이 한 걸음 먼저!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TAP_L2', 'accuracy', '순서대로 차근차근', '다음에 누를 숫자를 먼저 입으로 말하고, 화면에서 찾아서 눌러요.
급하게 누르면 옆 숫자를 누르기 쉬워요. 1, 2, 3… 하나씩 정확하게!', '누르기 전에 숫자를 소리 내어 말해 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TAP_L2', 'speed', '8초 안에 끝내려면', '실수 없이 잘 눌렀어요! 이제 다음 숫자가 어디 있는지 미리 눈으로 찾아 두면 빨라져요.
지금 숫자를 누르는 동안 눈은 벌써 다음 숫자를 찾고 있어야 해요.', '손보다 눈이 한 걸음 먼저!') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TAP_L3', 'accuracy', '순서대로 차근차근', '다음에 누를 숫자를 먼저 입으로 말하고, 화면에서 찾아서 눌러요.
급하게 누르면 옆 숫자를 누르기 쉬워요. 1, 2, 3… 하나씩 정확하게!', '누르기 전에 숫자를 소리 내어 말해 봐요.') on conflict do nothing;
insert into skill_explanations (skill_id, weakness, title, body, tip) values ('TAP_L3', 'speed', '5초 안에 끝내려면', '실수 없이 잘 눌렀어요! 이제 다음 숫자가 어디 있는지 미리 눈으로 찾아 두면 빨라져요.
지금 숫자를 누르는 동안 눈은 벌써 다음 숫자를 찾고 있어야 해요.', '손보다 눈이 한 걸음 먼저!') on conflict do nothing;
commit;
