-- 진단 평가 (assessment) tables — Postgres / Supabase.
-- Content only; student responses are a separate concern (see README "응답 저장").
-- Load order: schema.sql → seed.sql (generated by tools/build.py).

create table if not exists assessments (
  id                   text primary key,             -- 'rsm-4-7-diagnostic-2026-08'
  title                text not null,
  subtitle             text,
  publisher            text,
  source               jsonb,                        -- original file, conversion date, what was excluded
  grading_kinds        jsonb,                        -- how each blank kind is graded
  evaluation_template  jsonb,                        -- fields of the teacher's evaluation sheet (no student data)
  created_at           timestamptz not null default now()
);

create table if not exists assessment_sections (
  id             text primary key,                   -- '<assessment>:s01'
  assessment_id  text not null references assessments(id) on delete cascade,
  ord            int  not null,
  title          text not null,
  pdf_title      text,                               -- title as printed when the PDF has a numbering typo
  pdf_page       int,
  teacher_note   text,                               -- the blue "메모" guidance (teachers only)
  unique (assessment_id, ord)
);

create table if not exists assessment_parts (
  id          text primary key,                      -- '<section>:p1'  (left / right column of the page)
  section_id  text not null references assessment_sections(id) on delete cascade,
  ord         int  not null,
  title       text not null,                         -- may contain $latex$
  timed       boolean not null default false,        -- PDF shows "____초": record seconds for the column
  unique (section_id, ord)
);

create table if not exists assessment_items (
  id            text primary key,                    -- '<assessment>:s01-p1-01'
  part_id       text not null references assessment_parts(id) on delete cascade,
  ord           int  not null,
  label         text not null,                       -- '①', '1.', '3)'
  type          text not null check (type in ('fill','select_many','free','group')),
  grading       text not null check (grading in ('auto','manual','mixed')),
  stem          jsonb not null,                      -- [{t:'rich', v:'text $latex$'} | {t:'blank', id:'b1'}]
  blanks        jsonb not null default '[]',         -- [{id, kind, answer, accept?}] — answers: never send to students before submit
  choices       jsonb,                               -- select_many options
  model_answer  text,                                -- teacher-facing worked answer
  figure        text,                                -- 'figures/….svg'
  review_note   text,                                -- conversion assumption to confirm
  tags          text[],
  unique (part_id, ord)
);
create index if not exists assessment_items_tags on assessment_items using gin (tags);
