-- 잇고톡 MVP 스키마 (SQLite / Cloudflare D1). 설명은 docs/data-model.md 참고.
-- Applied by `wrangler d1 migrations apply` (D1) and by src/lib/db/migrate.ts (local SQLite).
--
-- SQLite conventions used by the app (src/lib/db/sqlite.ts converts on read/write):
--   ids         text uuid, generated by the default below
--   timestamps  text ISO-8601 UTC ('2026-10-05T12:34:56.789Z'); columns named *_at come back as Date
--   booleans    integer 0/1; known boolean columns come back as true/false
--   json        text; known json columns come back parsed
-- Access control (who may read which rows) is enforced in src/lib/db/scope.ts, not in the database.

-- ── 지역·학교·기관 ─────────────────────────────
create table regions (
  id          text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  name        text not null unique,            -- 예: 경기 양평군
  is_active   integer not null default 1
);

create table schools (
  id          text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  region_id   text not null references regions(id),
  name        text not null,
  level       text not null check (level in ('elementary','middle','high')),
  is_active   integer not null default 1,
  unique (region_id, name)
);

create table organizations (
  id           text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  name         text not null,
  kind         text not null check (kind in ('academy','study_room')),  -- 학원 / 공부방
  invite_code  text not null unique,
  created_at   text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ── 사용자 ─────────────────────────────────────
-- Login credentials (login id → scrypt hash). Only the server reads this table.
create table user_credentials (
  id                  text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  email               text not null unique,
  encrypted_password  text not null,
  created_at          text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create table profiles (
  id              text primary key references user_credentials(id),
  role            text not null check (role in ('student','teacher','org_admin','admin')),
  display_initial text not null,                -- 학생 화면 표시용 이니셜
  full_name       text,                         -- 교사·관리자만 화면에 노출
  grade           integer check (grade between 1 and 12),
  school_id       text references schools(id),
  organization_id text references organizations(id),
  is_approved     integer not null default 0,   -- 교사: 원장 승인 여부
  created_at      text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
create index profiles_org on profiles (organization_id, role);

create table guardians (
  id               text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  student_id       text not null references profiles(id) on delete cascade,
  phone            text not null,
  consent_at       text not null,                -- 법정대리인 동의 시각
  report_opt_in    integer not null default 1
);
create index guardians_student on guardians (student_id);

-- ── 콘텐츠 ─────────────────────────────────────
-- Learning tracks in 학습자료실 (덧셈과 뺄셈, 구구단, 1~9 빨리 누르기 …).
create table tracks (
  id              text primary key,
  ord             integer not null unique,
  name            text not null,
  description     text,
  icon            text,
  has_diagnostic  integer not null default 1
);

create table skills (
  id                 text primary key,           -- 예: ADD_P2_COMM
  ord                integer not null unique,    -- 진도 순서 (트랙을 통틀어 유일)
  track_id           text not null references tracks(id),
  book               text not null,              -- SA..SH
  week               integer,
  name               text not null,
  pattern            text not null check (pattern in ('intro','intuition','commutative','complement10','times_table','times_mixed','tap_sequence')),
  operand            integer,
  hint               text,
  time_rule          text not null default 'per_set' check (time_rule in ('per_set','per_item')),
  time_limit_sec     real not null default 12,
  practice_required  integer not null default 3
);
create index skills_track on skills (track_id, ord);

create table item_sets (
  id        text primary key,                    -- 예: SA-P09
  skill_id  text not null references skills(id),
  page      integer not null,
  ord       integer not null                     -- 스킬 내 순서
);
create index item_sets_skill on item_sets (skill_id, ord);

create table items (
  id        text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  set_id    text not null references item_sets(id) on delete cascade,
  ord       integer not null,
  a         integer not null,
  op        text not null check (op in ('+','-','×','÷')),
  b         integer not null,
  blank     text not null check (blank in ('result','operand2')),
  answer    integer not null,
  unique (set_id, ord)
);

-- Explanations shown after a diagnostic (or failed test), chosen by the weakness found.
create table skill_explanations (
  skill_id  text not null references skills(id) on delete cascade,
  weakness  text not null check (weakness in ('accuracy','speed')),
  title     text not null,
  body      text not null,
  tip       text,
  primary key (skill_id, weakness)
);

-- ── 학습 기록 ──────────────────────────────────
create table attempts (
  id                  text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  student_id          text not null references profiles(id),
  set_id              text not null references item_sets(id),
  mode                text not null check (mode in ('practice','test','diagnostic','race_ai')),
  item_count          integer not null,
  correct_count       integer not null,
  client_elapsed_ms   integer not null,
  server_started_at   text not null,
  server_finished_at  text not null,
  elapsed_ms          integer not null,          -- 엔진이 확정한 판정용 시간
  passed              integer,                   -- test/diagnostic만 값 있음
  wrong_items         text not null default '[]',  -- [{item_id, given, ...}]
  created_at          text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
create index attempts_student on attempts (student_id, created_at desc);

create table skill_progress (
  student_id         text not null references profiles(id),
  skill_id           text not null references skills(id),
  status             text not null check (status in ('locked','in_progress','passed')),
  current_set_id     text references item_sets(id),
  practice_count     integer not null default 0,
  consecutive_fail   integer not null default 0,
  best_elapsed_ms    integer,
  passed_at          text,
  primary key (student_id, skill_id)
);

-- Server-side clock for one play-through (rule 1: server verifies elapsed time).
-- item_order fixes which items, in which order, the student was shown.
create table play_sessions (
  id           text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  student_id   text not null references profiles(id),
  set_id       text not null references item_sets(id),
  mode         text not null check (mode in ('practice','test','diagnostic','race_ai')),
  item_order   text not null,                    -- [item_id, ...]
  ai_target_ms integer,                          -- race_ai only: AI finish time
  started_at   text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  finished_at  text,
  attempt_id   text references attempts(id)
);
create index play_sessions_student on play_sessions (student_id, started_at desc);
create index play_sessions_attempt on play_sessions (attempt_id);

-- learning-engine §3 assignReview(): previous skill's set to practise after 3 failed tests.
create table review_assignments (
  id            text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  student_id    text not null references profiles(id),
  skill_id      text not null references skills(id),
  set_id        text not null references item_sets(id),
  created_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  completed_at  text
);
create index review_assignments_open on review_assignments (student_id) where completed_at is null;

-- ── 교사·리포트 ────────────────────────────────
create table reports (
  id            text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  student_id    text not null references profiles(id),
  period_start  text not null,                   -- 'YYYY-MM-DD'
  period_end    text not null,
  lines         text not null,                   -- ["+3 교환법칙: 9/27 …", …]
  share_token   text not null unique,
  expires_at    text not null,
  sent_at       text,
  created_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
create index reports_student on reports (student_id, created_at desc);

create table comments (
  id          text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  author_id   text not null references profiles(id),
  attempt_id  text references attempts(id),
  report_id   text references reports(id) on delete cascade,
  body        text not null,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  check (attempt_id is not null or report_id is not null)
);

create table teacher_alerts (
  id          text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  student_id  text not null references profiles(id),
  skill_id    text not null references skills(id),
  reason      text not null,                     -- 'consecutive_fail_3'
  read_at     text,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
create index teacher_alerts_student on teacher_alerts (student_id, created_at desc);

-- Delivery log for parent report links (console now, KakaoTalk later).
create table report_deliveries (
  id          text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  report_id   text not null references reports(id) on delete cascade,
  channel     text not null,                     -- 'console' | 'email' | 'kakao'
  recipient   text not null,
  status      text not null check (status in ('sent','failed')),
  detail      text,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- 상담신청 (site /qa). Written by the server after validation; only admins read them.
create table inquiries (
  id          text primary key default (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
  name        text not null,
  phone       text not null,
  topic       text not null,
  message     text not null,
  consent_at  text not null,
  handled_at  text,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ── 진단 평가 (읽고 말하는 수학 4~7학년 테스트). 원본: content/assessment/schema.sql ──
-- Content only. Answers and teacher notes are hidden from plain users by src/lib/db/scope.ts.
create table assessments (
  id                   text primary key,             -- 'rsm-4-7-diagnostic-2026-08'
  title                text not null,
  subtitle             text,
  publisher            text,
  source               text,                         -- json: original file, conversion date, what was excluded
  grading_kinds        text,                         -- json: how each blank kind is graded
  evaluation_template  text,                         -- json: fields of the teacher's evaluation sheet
  created_at           text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create table assessment_sections (
  id             text primary key,                   -- '<assessment>:s01'
  assessment_id  text not null references assessments(id) on delete cascade,
  ord            integer not null,
  title          text not null,
  pdf_title      text,
  pdf_page       integer,
  teacher_note   text,                               -- the blue "메모" guidance (teachers only)
  unique (assessment_id, ord)
);

create table assessment_parts (
  id          text primary key,                      -- '<section>:p1'
  section_id  text not null references assessment_sections(id) on delete cascade,
  ord         integer not null,
  title       text not null,
  timed       integer not null default 0,
  unique (section_id, ord)
);

create table assessment_items (
  id            text primary key,                    -- '<assessment>:s01-p1-01'
  part_id       text not null references assessment_parts(id) on delete cascade,
  ord           integer not null,
  label         text not null,
  type          text not null check (type in ('fill','select_many','free','group')),
  grading       text not null check (grading in ('auto','manual','mixed')),
  stem          text not null,                       -- json
  blanks        text not null default '[]',          -- json [{id, kind, answer, accept?}] — never to students
  choices       text,                                -- json
  model_answer  text,
  figure        text,
  review_note   text,
  tags          text,                                -- json ["add_2d1d", …]
  unique (part_id, ord)
);
