/**
 * pnpm db:seed        → migrate + load content/*.csv into the local database (.data/pglite)
 * pnpm db:seed --reset → wipe the local database first (demo accounts are recreated)
 * pnpm db:seed:sql    → write supabase/seed.sql (content only) for `supabase db reset`
 *
 * Every item's answer is recomputed from a, op, b, blank; any mismatch aborts with the line number.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { validateExplanationsCsv } from "../src/lib/content/validate";
import { openDatabase } from "../src/lib/db/open";
import { ContentError, loadContentFiles, seedContentFromFiles } from "../src/lib/db/seed";

const args = new Set(process.argv.slice(2));

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  return `'${String(v).replaceAll("'", "''")}'`;
}

function writeSeedSql() {
  const { tracks, skills, items } = loadContentFiles();
  const out: string[] = ["-- Generated by `pnpm db:seed:sql` from content/*.csv. Do not edit by hand.", "begin;"];
  for (const t of tracks) {
    const vals = [t.id, t.ord, t.name, t.description, t.icon, t.hasDiagnostic ? "true" : "false"];
    out.push(`insert into tracks (id, ord, name, description, icon, has_diagnostic) values (${vals.slice(0, 5).map(sqlLiteral).join(", ")}, ${vals[5]}) on conflict (id) do update set ord = excluded.ord, name = excluded.name, description = excluded.description, icon = excluded.icon, has_diagnostic = excluded.has_diagnostic;`);
  }
  for (const s of skills) {
    const vals = [s.id, s.ord, s.book, s.week, s.name, s.pattern, s.operand, s.hint, s.timeRule, s.timeLimitSec, s.practiceRequired, s.trackId];
    out.push(
      `insert into skills (id, ord, book, week, name, pattern, operand, hint, time_rule, time_limit_sec, practice_required, track_id) values (${vals.map(sqlLiteral).join(", ")}) on conflict (id) do nothing;`,
    );
  }
  const sets = new Map<string, { skillId: string; page: number }>();
  for (const it of items) sets.set(it.setId, { skillId: it.skillId, page: it.page });
  for (const [id, s] of sets) {
    out.push(`insert into item_sets (id, skill_id, page, ord) values (${[id, s.skillId, s.page, 0].map(sqlLiteral).join(", ")}) on conflict (id) do nothing;`);
  }
  out.push(
    "update item_sets s set ord = r.rn from (select id, row_number() over (partition by skill_id order by page) as rn from item_sets) r where r.id = s.id;",
  );
  for (const it of items) {
    const vals = [it.setId, it.ord, it.a, it.op, it.b, it.blank, it.answer];
    out.push(`insert into items (set_id, ord, a, op, b, blank, answer) values (${vals.map(sqlLiteral).join(", ")}) on conflict (set_id, ord) do nothing;`);
  }
  const explanations = validateExplanationsCsv(readFileSync("content/explanations.csv", "utf8"), new Set(skills.map((s) => s.id)));
  if (!explanations.ok) throw new ContentError("explanations.csv", explanations.errors);
  for (const e of explanations.rows) {
    const vals = [e.skillId, e.weakness, e.title, e.body, e.tip || null];
    out.push(`insert into skill_explanations (skill_id, weakness, title, body, tip) values (${vals.map(sqlLiteral).join(", ")}) on conflict do nothing;`);
  }
  out.push("commit;", "");
  writeFileSync("supabase/seed.sql", out.join("\n"));
  console.log(`supabase/seed.sql: ${skills.length} skills, ${sets.size} sets, ${items.length} items`);
}

async function main() {
  if (args.has("--sql")) return writeSeedSql();
  const dataDir = process.env.ITGO_DATA_DIR ?? ".data/pglite";
  // openDatabase seeds content + demo accounts on an empty database.
  const db = await openDatabase({ dataDir, reset: args.has("--reset"), seedDemo: true });
  // Re-apply content so CSV edits reach an existing database.
  const r = await db.transaction((tx) => seedContentFromFiles(tx));
  console.log(`${dataDir}: ${r.skills} skills, ${r.sets} sets, ${r.items} items, ${r.explanations} explanations`);
  await db.close();
}

main().catch((e) => {
  if (e instanceof ContentError) {
    console.error(`콘텐츠 검증 실패 (${e.file})`);
    for (const err of e.errors) console.error(`  ${err.line}행: ${err.message}`);
  } else {
    console.error(e);
  }
  process.exit(1);
});
