/**
 * pnpm db:seed          → migrate + load content/*.csv into the local database (.data/itgotalk.sqlite)
 * pnpm db:seed --reset  → wipe the local database first (demo accounts are recreated)
 * pnpm db:seed:sql      → write .data/d1-seed.sql (content upserts) for Cloudflare D1:
 *                           wrangler d1 execute itgotalk --remote --file .data/d1-seed.sql
 * pnpm db:seed:sql --admin <loginId>
 *                       → also add a 본사 관리자 account; its password is generated and printed once
 *
 * Every item's answer is recomputed from a, op, b, blank; any mismatch aborts with the line number.
 */
import { randomBytes, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { hashPassword, loginIdToEmail } from "../src/lib/auth/password";
import { validateExplanationsCsv } from "../src/lib/content/validate";
import { openDatabase } from "../src/lib/db/open";
import { ContentError, loadContentFiles, seedContentFromFiles, upsertExplanations, upsertItems, upsertSkills, upsertTracks } from "../src/lib/db/seed";
import { encodeParam } from "../src/lib/db/sqlite";
import type { Tx } from "../src/lib/db/types";

const args = process.argv.slice(2);

function sqlLiteral(v: unknown): string {
  const e = encodeParam(v);
  if (e === null) return "null";
  if (typeof e === "number") return String(e);
  return `'${e.replaceAll("'", "''")}'`;
}

/** A Tx that records write statements with their parameters inlined, instead of running them. */
function recorder(out: string[]): Tx {
  return {
    query: async (sql, params = []) => {
      out.push(`${sql.replace(/\$(\d+)/g, (_, n: string) => sqlLiteral(params[Number(n) - 1])).trim()};`);
      return { rows: [] };
    },
    exec: async (sql) => out.push(sql),
  };
}

async function writeD1Sql() {
  const { tracks, skills, items } = loadContentFiles();
  const explanations = validateExplanationsCsv(readFileSync("content/explanations.csv", "utf8"), new Set(skills.map((s) => s.id)));
  if (!explanations.ok) throw new ContentError("explanations.csv", explanations.errors);

  const out: string[] = ["-- Generated by `pnpm db:seed:sql` from content/*.csv. Do not edit by hand."];
  const tx = recorder(out);
  await upsertTracks(tx, tracks);
  await upsertSkills(tx, skills);
  await upsertItems(tx, items);
  await upsertExplanations(tx, explanations.rows);

  const i = args.indexOf("--admin");
  let admin: { loginId: string; password: string } | null = null;
  if (i >= 0) {
    const loginId = (args[i + 1] ?? "").toLowerCase();
    if (!/^[a-z0-9_]{4,20}$/.test(loginId)) throw new Error("--admin 다음에 아이디(영어 소문자·숫자 4~20자)를 적어 주세요.");
    admin = { loginId, password: randomBytes(9).toString("base64url") };
    const id = randomUUID();
    out.push(
      `insert into user_credentials (id, email, encrypted_password) values (${sqlLiteral(id)}, ${sqlLiteral(loginIdToEmail(loginId))}, ${sqlLiteral(await hashPassword(admin.password))});`,
      `insert into profiles (id, role, display_initial, full_name, is_approved) values (${sqlLiteral(id)}, 'admin', '관리', '본사 관리자', 1);`,
    );
  }

  mkdirSync(".data", { recursive: true });
  writeFileSync(".data/d1-seed.sql", out.join("\n") + "\n");
  console.log(`.data/d1-seed.sql: ${tracks.length} tracks, ${skills.length} skills, ${items.length} items, ${explanations.rows.length} explanations`);
  if (admin) console.log(`본사 관리자 → 아이디: ${admin.loginId}  비밀번호: ${admin.password}  (다시 표시되지 않으니 지금 적어 두세요)`);
}

async function main() {
  if (args.includes("--sql")) return writeD1Sql();
  const dataDir = process.env.ITGO_DATA_DIR ?? ".data";
  // openDatabase seeds content + demo accounts on an empty database.
  const db = await openDatabase({ dataDir, reset: args.includes("--reset"), seedDemo: true });
  // Re-apply content so CSV edits reach an existing database.
  const r = await seedContentFromFiles(db);
  console.log(`${dataDir}/itgotalk.sqlite: ${r.skills} skills, ${r.sets} sets, ${r.items} items, ${r.explanations} explanations`);
  await db.close();
}

main().catch((e) => {
  if (e instanceof ContentError) {
    console.error(`콘텐츠 검증 실패 (${e.file})`);
    for (const err of e.errors) console.error(`  ${err.line}행: ${err.message}`);
  } else {
    console.error(e);
  }
  process.exit(1);
});
